<a href="https://colab.research.google.com/github/PawanKrGunjan/DataScience_tutorial/blob/main/Naive_Bayes_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!wget -O run_or_walk.csv https://raw.githubusercontent.com/JangirSumit/data_science/master/2nd%20June%20Assignments/case%20study%202/run_or_walk.csv

--2022-02-13 06:34:33--  https://raw.githubusercontent.com/JangirSumit/data_science/master/2nd%20June%20Assignments/case%20study%202/run_or_walk.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7501300 (7.2M) [text/plain]
Saving to: ‘run_or_walk.csv’

run_or_walk.csv     100%[===================>]   7.15M  --.-KB/s    in 0.07s   

2022-02-13 06:34:33 (104 MB/s) - ‘run_or_walk.csv’ saved [7501300/7501300]



In [ ]:
df = pd.read_csv("run_or_walk.csv", delimiter=",")
df.head()

date                time username  ...  gyro_x  gyro_y  gyro_z
0  2017-6-30  13:51:15:847724020   viktor  ... -0.0590  0.0325 -2.9296
1  2017-6-30  13:51:16:246945023   viktor  ... -0.1757  0.0208  0.1269
2  2017-6-30  13:51:16:446233987   viktor  ... -0.9105  0.1063 -2.4367
3  2017-6-30  13:51:16:646117985   viktor  ...  0.1199 -0.4099 -2.9336
4  2017-6-30  13:51:16:846738994   viktor  ...  0.0527  0.4379  2.4922

[5 rows x 11 columns]

In [ ]:
df.shape

(88588, 11)

In [ ]:
df.describe()

wrist      activity  ...        gyro_y        gyro_z
count  88588.000000  88588.000000  ...  88588.000000  88588.000000
mean       0.522170      0.500801  ...      0.037203      0.022327
std        0.499511      0.500002  ...      1.198725      1.914423
min        0.000000      0.000000  ...     -7.464700     -9.480000
25%        0.000000      0.000000  ...     -0.644825     -1.345125
50%        1.000000      1.000000  ...      0.039300      0.006900
75%        1.000000      1.000000  ...      0.733700      1.398200
max        1.000000      1.000000  ...      8.498000     11.266200

[8 rows x 8 columns]

In [ ]:
df.isnull().any()

date              False
time              False
username          False
wrist             False
activity          False
acceleration_x    False
acceleration_y    False
acceleration_z    False
gyro_x            False
gyro_y            False
gyro_z            False
dtype: bool

**Features**: The characteristics that define your problem. These are also called attributes.

**Parameters**: The variables your algorithm is trying to tune to build an accurate model.

In [ ]:
features=df.columns
features

Index(['date', 'time', 'username', 'wrist', 'activity', 'acceleration_x',
       'acceleration_y', 'acceleration_z', 'gyro_x', 'gyro_y', 'gyro_z'],
      dtype='object')

In [ ]:
p=df.drop(['date',	'time',	'username',	'wrist',	'activity'], axis='columns')
p

acceleration_x  acceleration_y  acceleration_z  gyro_x  gyro_y  gyro_z
0              0.2650         -0.7814         -0.0076 -0.0590  0.0325 -2.9296
1              0.6722         -1.1233         -0.2344 -0.1757  0.0208  0.1269
2              0.4399         -1.4817          0.0722 -0.9105  0.1063 -2.4367
3              0.3031         -0.8125          0.0888  0.1199 -0.4099 -2.9336
4              0.4814         -0.9312          0.0359  0.0527  0.4379  2.4922
...               ...             ...             ...     ...     ...     ...
88583          0.3084         -0.8376         -0.1327  0.4823  2.0124  0.6048
88584          0.4977         -1.0027         -0.4397  0.1022 -1.2565 -0.0761
88585          0.4587         -1.1780         -0.2827 -1.4500 -0.2792 -1.2616
88586          0.2590         -0.8582         -0.0759 -1.5165  0.4560 -1.7755
88587          0.3140         -0.8008         -0.0911  0.1183  1.0850  1.2814

[88588 rows x 6 columns]

In [ ]:
target = df.activity
target

0        0
1        0
2        0
3        0
4        0
        ..
88583    0
88584    0
88585    0
88586    0
88587    0
Name: activity, Length: 88588, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x, y = p.values,target.values
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [ ]:
print( "x_train\n",x_train)
print("y_train\n",y_train)

x_train
 [[-0.3086 -0.61   -0.102   0.4219  0.0981 -0.4392]
 [-1.662   0.8219 -0.003  -2.1674 -1.4651 -0.6471]
 [-0.223  -0.6632 -0.1409 -0.6979  0.2005  0.75  ]
 ...
 [-0.1474 -0.4801  0.206  -1.0303 -0.0873 -0.3875]
 [-0.2881 -1.4325 -0.2796  1.382   1.8339 -1.9777]
 [ 0.3038 -1.1551 -0.3     1.6575 -1.2062  2.1936]]
y_train
 [0 1 0 ... 1 0 0]


In [ ]:
print("Shape of x_train\n",x_train.shape)
print("Shape of y_train\n",y_train.shape)

Shape of x_train
 (70870, 6)
Shape of y_train
 (70870,)


In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [ ]:
model.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_predict = model.predict(x_test)
y_predict

array([0, 0, 0, ..., 0, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy = accuracy_score(y_predict,y_test)
accuracy

0.9554690145614629

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
c_matrix =confusion_matrix(y_predict,y_test)
c_matrix

array([[8583,  699],
       [  90, 8346]])

In [ ]:
from sklearn.metrics import classification_report
target_names = ["Walk","Run"]

In [ ]:
print(classification_report(y_test, y_predict, target_names=target_names))

              precision    recall  f1-score   support

        Walk       0.92      0.99      0.96      8673
         Run       0.99      0.92      0.95      9045

    accuracy                           0.96     17718
   macro avg       0.96      0.96      0.96     17718
weighted avg       0.96      0.96      0.96     17718



**Repeat the model once using only the acceleration values as predictors and then using only the gyro values as predictors.**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88588 entries, 0 to 88587
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   date            88588 non-null  object 
 1   time            88588 non-null  object 
 2   username        88588 non-null  object 
 3   wrist           88588 non-null  int64  
 4   activity        88588 non-null  int64  
 5   acceleration_x  88588 non-null  float64
 6   acceleration_y  88588 non-null  float64
 7   acceleration_z  88588 non-null  float64
 8   gyro_x          88588 non-null  float64
 9   gyro_y          88588 non-null  float64
 10  gyro_z          88588 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 7.4+ MB


In [ ]:
variables= df.iloc[:, [5,6,7]]
variables[:5]

acceleration_x  acceleration_y  acceleration_z
0          0.2650         -0.7814         -0.0076
1          0.6722         -1.1233         -0.2344
2          0.4399         -1.4817          0.0722
3          0.3031         -0.8125          0.0888
4          0.4814         -0.9312          0.0359

In [ ]:
target2=df.iloc[:, 4]
target2

0        0
1        0
2        0
3        0
4        0
        ..
88583    0
88584    0
88585    0
88586    0
88587    0
Name: activity, Length: 88588, dtype: int64

In [ ]:
X, Y = variables.values,target2.values
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1)
print( "X_train\n",X_train)
print("Y_train\n",Y_train)

X_train
 [[-0.3086 -0.61   -0.102 ]
 [-1.662   0.8219 -0.003 ]
 [-0.223  -0.6632 -0.1409]
 ...
 [-0.1474 -0.4801  0.206 ]
 [-0.2881 -1.4325 -0.2796]
 [ 0.3038 -1.1551 -0.3   ]]
Y_train
 [0 1 0 ... 1 0 0]


In [ ]:
print("Shape of X_train\n",X_train.shape)
print("Shape of Y_train\n",Y_train.shape)

Shape of X_train
 (70870, 3)
Shape of Y_train
 (70870,)


In [ ]:
model.fit(X_train,Y_train)

GaussianNB()

In [ ]:
Y_predict = model.predict(X_test)
y_predict

array([0, 0, 0, ..., 0, 1, 1])

In [ ]:
accuracy = accuracy_score(Y_predict,Y_test)
accuracy

0.9565978101365843

In [ ]:
c_matrix =confusion_matrix(Y_predict,Y_test)
c_matrix

array([[8610,  706],
       [  63, 8339]])

In [ ]:
from sklearn.metrics import classification_report
target_names = ["Walk","Run"]
print(classification_report(Y_test, Y_predict, target_names=target_names))

              precision    recall  f1-score   support

        Walk       0.92      0.99      0.96      8673
         Run       0.99      0.92      0.96      9045

    accuracy                           0.96     17718
   macro avg       0.96      0.96      0.96     17718
weighted avg       0.96      0.96      0.96     17718

