In [1]:
print('Jai Shri Ganesh')

Jai Shri Ganesh


In [2]:
import numpy as np

In [3]:
myarr = np.array([1,2,3,4,5,7])

In [4]:
myarr

array([1, 2, 3, 4, 5, 7])

In [5]:
print(myarr)

[1 2 3 4 5 7]


In [6]:
myarr = np.array([1,2,3,4,5,7], np.int8)

In [7]:
myarr

array([1, 2, 3, 4, 5, 7], dtype=int8)

**Wrong Result**

In [8]:
myarr1 = np.array([1,2,3,4,5999999,7000],np.int8)
myarr1

array([  1,   2,   3,   4, 127,  88], dtype=int8)

In [9]:
myarr1 = np.array([1,2,3,4,5999999,7000],np.int64)
myarr1

array([      1,       2,       3,       4, 5999999,    7000])

In [10]:
myarr2=np.array([[7,8,9],[2,3,9]])
myarr2

array([[7, 8, 9],
       [2, 3, 9]])

In [11]:
myarr2.dtype

dtype('int64')

In [12]:
myarr2.shape

(2, 3)

In [13]:
myarr2.size

6

In [14]:
myarr2[1,2]

9

In [15]:
myarr2[1,1]

3

#Array Creation : Conversion from other Python Structure

In [16]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
print(listarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
listarray.shape

(3, 3)

In [19]:
listarray.size

9

In [20]:
listarray.dtype

dtype('int64')

In [21]:
np.array({12,35,70})

array({35, 12, 70}, dtype=object)

**Intrinsic Array Creation Objects**

In [22]:
zeros=np.zeros((2,5))

In [23]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
zeros.dtype

dtype('float64')

In [25]:
zeros.shape

(2, 5)

In [26]:
zeros.size

10

In [27]:
Range=np.arange(15)

In [28]:
Range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
Range.dtype

dtype('int64')

In [30]:
Range.size

15

In [31]:
Range.shape

(15,)

In [32]:
lspace=np.linspace(1,10,4)

In [33]:
lspace

array([ 1.,  4.,  7., 10.])

In [34]:
emp=np.empty((4,6))

In [35]:
emp

array([[4.64936272e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [36]:
emplike=np.empty_like(lspace)

In [37]:
emplike

array([ 1.,  4.,  7., 10.])

In [38]:
ide=np.identity(45)

In [39]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [40]:
ide.shape

(45, 45)

In [41]:
ide.size

2025

In [42]:
arr=np.arange(99)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr.shape

(99,)

In [45]:
arr.size

99

In [46]:
arr=arr.reshape(3,33)

In [47]:
#arr.reshape(3,31)

In [48]:
arr=arr.ravel()

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
arr.ravel

<function ndarray.ravel>

In [51]:
arr.shape

(99,)

In [52]:
x= [[1,2,3],[4,5,6],[7,1,0]]

In [53]:
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [54]:
ar=np.array(x)

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
ar.sum(axis=0)

array([12,  8,  9])

In [57]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [58]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [59]:
ar.flat


In [60]:
for item in ar.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [61]:
ar.ndim

2

In [62]:
arr.ndim

1

In [63]:
ar.size

9

In [64]:
ar.nbytes

72

**Sorting in term of indices**

In [65]:
one=np.array([1,3,4,634,2])

In [66]:
one.argmax()

3

In [67]:
one.argmin()

0

In [68]:
one.argsort()

array([0, 4, 1, 2, 3])

In [69]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
ar.argmax()

6

In [71]:
ar.argmin()

8

In [72]:
ar.argmax(axis=0)

array([2, 1, 1])

In [73]:
ar.argmin(axis=1)

array([0, 0, 2])

In [74]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [75]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [76]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [77]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [78]:
x=ar
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [79]:
ar2=[[1,2,1],[4,0,6],[8,1,0]]
ar2

[[1, 2, 1], [4, 0, 6], [8, 1, 0]]

In [80]:
y=np.array(ar2)

In [81]:
y

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [82]:
x+y

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [83]:
x*y

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [84]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [85]:
x.sum()

29

In [86]:
x.max()

7

In [87]:
x.min()

0

In [88]:
np.where(x>5)

(array([1, 2]), array([2, 0]))

In [89]:
type(np.where(x>5))

tuple

In [90]:
np.count_nonzero(x)

8

In [91]:
np.nonzero(x)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [92]:
x[1,2]=0

In [93]:
np.nonzero(x)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [94]:
import sys

In [95]:
py_ar=[0,4,55,2]

In [96]:
np_ar=np.array(py_ar)

In [97]:
sys.getsizeof(1)*len(py_ar)

112

In [98]:
np_ar.itemsize*np_ar.size

32

In [99]:
#https://docs.scipy.org/doc//numpy-1.17.0/reference/arrays.ndarray.html

https://docs.scipy.org/doc//numpy-1.17.0/reference/arrays.ndarray.html